### ISSUE TITLE
Implement simple tap gestures.

### ISSUE THREAD

**Issue by pragmatrix** [pragmatrix/emergent#23]
Time to get interactive.

Right now, tap gestures are required to be able..
- [ ] to tap on a filename in the compiler message to open the IDE at that point.
  > postponed
- [x] to collapse individual testcases or modules. 

The plan:

- [x] Introduce the concept of _area markers_ in the drawings. These are markers representing drawing rectangles that are computed with the `*FastBounds` trait family. #31 
- [x] Then a new type called `Presentation` is used as the default output of a testcase _and_ an application. A `Presentation` combines drawings, gesture detection requests based on area markers, and event template serialization. #31 
- [x] Introduce a new package `emergent-presentation` in the subfolder `presentation/` (#31):
  - [x] Support event templates. These are the events an application may receive, including _holes_ to fill in additional information. The holes may be filled in by convention, or generic types?
    > not needed anymore, see blow.
  - [x] Support for visualizing presentations: This should include the gestures requested, the event templates and the markers involved.
    > Basic visualization is implemented, but named areas and scopes must be added.

Issues:
- [x] If monotonically increasing unique ids are used to represent the markers, how can snapshot testing be supported for the output of individual testcases?  
  > not needed, `&'static str`s are used up area identities by introducing namespaces / scopes.
- [x] Can event templates be strongly typed so that the information the gesture detector may provide be mapped to them? Of course all fields are optional. For example a tap gesture detector may provide `taps_count`, `positions`, `position` (the first one), `global_positions` screen relative position, etc.
  One idea is to provide a (pure!) function that takes the arguments of the recognizer state. The serializer creates a arbibtrary marker state, calls the function with it, and then replaces the values that survived with references that are filled in later.
  > Not using templates anymore, the part of the presentation that cannot be serialized stays inside the WindowApplication wrapper.
- [ ] How can the returned positions be mapped to other elements / drawing areas from within the application?
  > Postponed.
